### PR TITLE
Fix Size of pullquotes under headers is wrong/inconsistent

### PR DESCRIPTION
**Pull request by ashokmladumor**

### CODE REVIEW

**Comment by ashokmladumor** [comment]
@andrewheins  I've sorted out the headers pullquote problem from the backend. Also, I noticed a design issue with the content pullquote, so I took care of that as well.

**Comment by andrewheins** [comment]
This looks good. Thanks @ashokmladumor

**Comment by andrewheins** [comment]
@ashokmladumor  Where was the issue in the back-end? We're not seeing the change on the page (about, for example still has an oversized pullquote). Is this something we need to change in the content?

**Comment by ashokmladumor** [comment]
> pullquote

@andrewheins  Yes, I've made two changes in the backend block. I've attached an image for reference.

image_2024_03_02T12_32_28_005Z (2)

**Comment by slambert** [comment]
Hi @ashokmladumor Does that mean those options are enabled by default moving forward? What I was hoping for was to fix everything that was too large/bold so we wouldn't have to go back and change older posts. 

If so, maybe we could do your fix combined with a very specific search and replace?

**Pull request merged**
